### ISSUE TITLE
playWhenReady: true

### ISSUE THREAD

**Issue by Loukili-Rachid** [Pisey-Nguon/Flutter_Native_Player#1]
Hello everyone this bool : playWhenReady: true / false not working always the player autoplay

**Comment by Pisey-Nguon** [comment]
Thank for your comment I will check this issue as soon as possible.

**Comment by Pisey-Nguon** [comment]
> Hello everyone this bool : playWhenReady: true / false not working always the player autoplay

We have already fixed this issue let's take a look at version **1.0.6** and feel free to reopen this issue if you still occur this issue
